// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App struct
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

/**
 * GetMdContent
 * @returns {Promise<{ [_: string]: any }> & { cancel(): void }}
 */
export function GetMdContent() {
    let $resultPromise = /** @type {any} */($Call.ByID(2023825735));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType0($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * GoNewFile
 * @returns {Promise<string> & { cancel(): void }}
 */
export function GoNewFile() {
    let $resultPromise = /** @type {any} */($Call.ByID(3323072461));
    return $resultPromise;
}

/**
 * goOpenFile
 * @returns {Promise<{ [_: string]: any }> & { cancel(): void }}
 */
export function GoOpenFile() {
    let $resultPromise = /** @type {any} */($Call.ByID(496402785));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType0($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * GoSaveAsFile resutl: {"value": "OK", "filename": "e:\\StXhCode\\go\\mdPad\\untitle.md"}
 * @param {string} content
 * @returns {Promise<{ [_: string]: any }> & { cancel(): void }}
 */
export function GoSaveAsFile(content) {
    let $resultPromise = /** @type {any} */($Call.ByID(4275237596, content));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType0($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * GoSaveFile
 * @param {string} content
 * @returns {Promise<string> & { cancel(): void }}
 */
export function GoSaveFile(content) {
    let $resultPromise = /** @type {any} */($Call.ByID(4032945048, content));
    return $resultPromise;
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
