// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetMdContent():Promise<{[key: string]: any}>;

export function GoNewFile():Promise<string>;

export function GoOpenFile():Promise<{[key: string]: any}>;

export function GoSaveAsFile(arg1:string):Promise<{[key: string]: any}>;

export function GoSaveFile(arg1:string):Promise<string>;
