// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetMdContent() {
  return window['go']['main']['App']['GetMdContent']();
}

export function GoNewFile() {
  return window['go']['main']['App']['GoNewFile']();
}

export function GoOpenFile() {
  return window['go']['main']['App']['GoOpenFile']();
}

export function GoSaveAsFile(arg1) {
  return window['go']['main']['App']['GoSaveAsFile'](arg1);
}

export function GoSaveFile(arg1) {
  return window['go']['main']['App']['GoSaveFile'](arg1);
}
