name: Wails build

on:
  push:
    tags:
      # Match any new tag
      - "*"

env:
  # Necessary for most environments as build failure can occur due to OOM issues
  NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
  build:
    strategy:
      # Failure in one platform build won't impact the others
      fail-fast: false
      matrix:
        build:
          - name: "App"
            platform: "linux/amd64"
            os: "ubuntu-latest"
          - name: "App"
            platform: "windows/amd64"
            os: "windows-latest"
          - name: "mdPad"
            platform: "darwin/universal"
            os: "macos-latest"

    runs-on: "ubuntu-latest"
    steps:
      - name: Update package list
        run: sudo apt-get update

      - name: Install dependencies
        run: sudo apt-get install -y libwebkit2gtk-4.0-dev

    runs-on: ${{ matrix.build.os }}
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install Bun
        uses: oven-sh/setup-bun@v1 # Use the official setup-bun action
        with:
          bun-version: latest # Or a specific version like '1.0.0'

      - name: Install dependencies
        run: cd frontend && bun install

      #- name: Build
      #  run: cd frontend && bun run build # Or your build command

      - name: Build wails
        uses: dAppServer/wails-build-action@v2.2
        id: build
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          package: false
          go-version: "1.23"

      # Upload build assets
      - uses: actions/upload-artifact@v3
        if: inputs.package == 'true'
        with:
          name: Wails Build ${{runner.os}} ${{inputs.build-name}}
          path: |
            */bin/
            *\bin\*

      - name: Release
        uses: softprops/action-gh-release@v1
        if: inputs.package == 'true' && startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            */bin/*
